#!/bin/bash
#$ -pe smp* 1                      # mpi env 16 cores (1 node)
#$ -N cupt                         # job name
#$ -q henryd.q@henryd03.prv.gravity   # queue name
#$ -cwd                               # launch from current working directory

###
export OMP_NUM_THREADS=1
export MKL_NUM_THREADS=1
####

~/sharedscratch/BH-PEW/bh_pew < input_bh.in > output.out
